### PR TITLE
connect-inject issue 36: fix for service registration in consul

### PR DESCRIPTION
**Pull request by pavel-mikhalchuk**
Register service in consul with pod name provided by downward api. 
See https://github.com/hashicorp/consul-k8s/issues/36.

### CODE REVIEW

**Comment by pavel-mikhalchuk** [comment]
I wish I could push it with set of unit test but I want it get fixed so badly :)

**Comment by BarthV** [comment]
hi @pavel-mikhalchuk . Do you plan to merge this PR ?
Do you need any help to make it works ?

Thanks :)

**Comment by adilyse** [comment]
Merged #55  which includes these changes with additional tests. Thanks for the contribution!

**Comment by pavel-mikhalchuk** [comment]
@nicholasjackson, sorry was distracted from this for some time. 

@adilyse, my pleasure! Now we can get on consul-connect in our k8s cluster :)

**Pull request closed without merging**
