### PR TITLE
Add readOnlyRootFilesystem to security context

### PR DESCRIPTION
**Pull request by mr-miles**
Changes proposed in this PR:
- Explicitly label container security context as having a readonly root filesystem

How I've tested this PR:

I was attempting to run consul in a restricted namespace and our gatekeeper policy tripper on this.  I found I could not add the context by manipulating the helm values and so a PR was required,

I have tested it by deploying my updated package and confirming gatekeeper was not tripped

How I expect reviewers to test this PR:

Confirm it deploys fine in a standard test environment just for sanity: as the components don't write this labelling doesn't affect functionality and so is a no-op for anyone not already blocked by  security context.

Checklist:
- [ ] Tests added
- [ ] [CHANGELOG entry added](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by david-yu** [comment]
@mr-miles Could you tell us how you are using GateKeeper and why a policy in gatekeeper is requiring this? Thanks for the PR.

**Comment by mr-miles** [comment]
Sorry @david-yu, you caught this before I'd made a ticket with more explanation in!

Our network team use gatekeeper to enforce their security policy over our k8s cluster and previously consul was exempted from all the checks.  There were a couple of updates to the helm chart recently to allow consul + sidecar to run in a restricted/unprivileged environment so we attempted to re-enabled it. 

On doing so, our "readonlyfilesystem" validation was flagging, and preventing sidecars from starting (I think our restricted environment is a little more restricted than just non-root user accounts).  The change to readonly containers was small - but useful security hardening (plus it has caught some bugs for us in other areas in the past) - hence submitting a PR.  Do you think this is a useful addition?

**Comment by david-yu** [comment]
Sorry did you mean you used the latest changes from https://github.com/hashicorp/consul-k8s/pull/2755 to run in an un-privileged mode, and these were extra settings needed to allow your sidecars to run? In this case gateways are writing to `tempfs ` instead of disk?

**Comment by mr-miles** [comment]
Yes that's it - they are extra settings that I needed to make everything work.  Though it was the changes in #2702 and #2572 that I had been looking at.

Thinking about it, it doesn't need to be medium=memory since the bootstrap file doesn't have anything sensitive in.  Any mount (disk or memory) of /tmp will avoid the "container filesystem is readonly" error message.

**Review by pglass — APPROVED** [review]

**Comment by pglass** [comment]
@mr-miles If you can copy over this Helm chart unit test fix: https://github.com/hashicorp/consul-k8s/pull/2788/commits/d38380c088aa6722421f45cc122d29d909577d66, then this PR should be good to merge from my perspective.

(Our CI tests currently won't run successfully for PRs created forks unfortunately 😞)

**Comment by mr-miles** [comment]
@pglass - thanks for looking at this - done!

**Comment by david-yu** [comment]
What version of the Helm chart are you? @mr-miles trying to understand what releases to backport this into. We can at least do consul k8s 1.2.x.

**Comment by mr-miles** [comment]
1.2.x is fine for me - we're on 1.2.1

**Pull request merged**
