### PR TITLE
Change references of `master` to `main`

### PR DESCRIPTION
**Pull request by t-eckert**
> 🚨 Do not merge until `master` is renamed to `main`

Changes proposed in this PR:
- All meaningful references to `master` have been changed to reference `main`
  I grepped for `master` in the repo and filtered out instances that did not refer to the repo itself (e.g. master token) or referred to other repositories. Then I replaced the remaining instances.

How I've tested this PR:  
This is a hard one to test. I'm very open to suggestions.

### CODE REVIEW

**Review by ndhanushkodi — COMMENTED** [review]
I think [.circleci/config.yml L890](https://github.com/hashicorp/consul-k8s/blob/master/.circleci/config.yml#L890) needs to change as well but otherwise I think this is looking good!

**Comment by t-eckert** [comment]
@ndhanushkodi, you are absolutely right. Great catch.

**Review by ishustava — APPROVED** [review]
Looks great, Thomas!

There is just one more reference that need to be updated in the `update-helm-charts-index` job where we make a curl request and mention the branch in the payload ` -d "{\"branch\": \"master\",\"parameters\":{\"SOURCE_REPO\": \"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\",\"SOURCE_TAG\": \"${CIRCLE_TAG}\"}}"`

**Comment by t-eckert** [comment]
@ishustava, fixed! Another good catch. I saw that one but thought it was for an external repo.

**Comment by ndhanushkodi** [comment]
> There is just one more reference that need to be updated in the `update-helm-charts-index` job where we make a curl request and mention the branch in the payload ` -d "{\"branch\": \"master\",\"parameters\":{\"SOURCE_REPO\": \"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\",\"SOURCE_TAG\": \"${CIRCLE_TAG}\"}}"`

@t-eckert I just talked to Iryna about this as well, and this one should stay as master, since that's the branch of the pipeline being triggered via the circleci api (https://circleci.com/docs/api/v2/#operation/triggerPipeline).

**Comment by t-eckert** [comment]
@ndhanushkodi @ishustava, cool. I just pulled that commit out of history. Should be all set now. @ndhanushkodi, go on vacation. I'll tag someone else for the second sign off tomorrow :)

**Comment by ishustava** [comment]
Thank you so much! Sorry for the confusion!!

**Comment by t-eckert** [comment]
@ishustava That's why we all do this together! :)

**Review by lkysow — APPROVED** [review]

**Pull request merged**
