### PR TITLE
added imagePullPolicy for images in values.yaml (#2310)

### PR DESCRIPTION
**Pull request by aahel**
* added imagePullPolicy for images in values.yaml

* fix: renamed pullPolicy key according to image

* fixed dafault always in tmpl

* changed structure of image in yaml

* revert changes

* added global imagePullPolicy

* fixed typo

* added changelog file

Changes proposed in this PR:
-
-

How I've tested this PR:

How I expect reviewers to test this PR:

Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Review by thisisnotashwin — APPROVED** [review]

**Comment by aahel** [comment]
@thisisnotashwin a lot of acceptance tests are failing. even after rerun. is it safe to merge ?

**Comment by thisisnotashwin** [comment]
> @thisisnotashwin a lot of acceptance tests are failing. even after rerun. is it safe to merge ?

hmm. i dont think it is safe to assume that merging would be safe. i would look into the logs of the failures to check if it has anything to do with these changes and if something else has caused this just to play it safe.

**Comment by david-yu** [comment]
@aahel I'm guessing you probably need to rebase this PR to get the PRs to pass?

**Comment by aahel** [comment]
> @aahel I'm guessing you probably need to rebase this PR to get the PRs to pass?

did a rebase. still the acceptance tests are failing.

**Comment by aahel** [comment]
> @aahel I'm guessing you probably need to rebase this PR to get the PRs to pass?

@david-yu  Most likely this is due to the pipeline issue. Should i wait till that is fixed ?

**Comment by thisisnotashwin** [comment]
Closing this PR as the original PR has been reverted and will need to be reworked.

**Pull request closed without merging**
