### PR TITLE
Handle errors properly when services are de-registered from the catalog

### PR DESCRIPTION
**Pull request by mr-miles**
Possible fix for #2085 #2065 hashicorp/consul#15908 #1935 #1817 which are all the same issue of ghost services left in the catalog when nodes are recycled. Associated issue: https://github.com/hashicorp/consul-k8s/issues/2491

Changes proposed in this PR:
- Handle errors that occur when using the api to list existing nodes+services.  Previously these exceptions were dropped.

How I've tested this PR:
- I have run the unit tests
- I would like to write a test to simulate an error condition but my knowledge of go is not strong enough 

How I expect reviewers to test this PR:
- Confirm logic

Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by mr-miles** [comment]
I have been running this for the past two weeks and it has eliminated the issue of dead services in the catalog which we were seeing

**Comment by david-yu** [comment]
Thanks for the PR @mr-miles. I'll have the team take a look.

**Comment by mr-miles** [comment]
Thanks @david-yu - please feel free to contact me direct if you find you need any input.  The bug is quite painful for us so keen to help however I can!

**Comment by justin-sto** [comment]
Hi guys, @david-yu  is there any update on this? Or is there any way, how I can temporarily fix this? This is preventing us from upgrading our clusters, as they are shut down if not needed.

Thanks in advance

**Comment by curtbushko** [comment]
Hi @justin-sto I am working on a PR #2571 for this right now. It should be merged to main tomorrow (Friday) and most likely backported to several other release branches.

What version of consul-k8s are your running right now?

**Comment by curtbushko** [comment]
Replacing this PR in favour of #2571

**Comment by justin-sto** [comment]
> Hi @justin-sto I am working on a PR #2571 for this right now. It should be merged to main tomorrow (Friday) and most likely backported to several other release branches.
> 
> What version of consul-k8s are your running right now?

Hi @curtbushko thank you so much for merging that. Can´t await the release.
We wanted to upgrade to K8s 1.26, which did not work for us, cause of this exact issue with restarting the clusters.

Thanks again also to @mr-miles for figuring this out :)

**Comment by justin-sto** [comment]
Hi @curtbushko sorry for asking again, but do you know by any chance, when the change is going to be implemented into a new release? Unfortunately, I am stuck with this issue without a new image that I can deploy.

Thanks again for your help

**Comment by curtbushko** [comment]
@justin-sto Don't hold me to this exact timeline but we are looking to release patches late September/early October.

If you are stuck, you can [build your own image](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md) using the release branch you are on or use a dev image that is listed in the helm chart? As an example, for the next 1.1.x release, the dev image is in the [values.yaml file](https://github.com/hashicorp/consul-k8s/blob/release/1.1.x/charts/consul/values.yaml#L89). Each release has a corresponding image tag.

Note: the only difference for the binary between a dev image and a release image is the version number. We change that number and release the code that is on the release branch.

**Comment by justin-sto** [comment]
@curtbushko thanks for the update.
In this case, I will create my own image. Thanks for sharing the link on how to create the image.

**Comment by curtbushko** [comment]
@justin-sto You're welcome. Please feel free to tag/ping me here if you have problems.

**Comment by justin-sto** [comment]
@curtbushko I now used the dev image and the issue seems finally fixed. 
Thanks again for your help

**Comment by david-yu** [comment]
@justin-sto good to know that the PR fixed the issue and thank you to @mr-miles for doing the brunt of the legwork! A slight clarification, the fix should be released on Consul K8s 1.0.x, 1.1.x, and 1.2.x by mid august timeframe for our patch release cycle. We have a roughly 6 week cadence of patch releases.

**Pull request closed without merging**
