### PR TITLE
CHANGELOG updates for 1.0

### PR DESCRIPTION
**Pull request by curtbushko**
Changes proposed in this PR:
- I went back through all the PRs until the last release in October when the last check was done.

How I've tested this PR:

How I expect reviewers to test this PR:

:eyes:

Checklist:
- [ ] Tests added
- [X] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by david-yu** [comment]
Thanks, could you pull in my latest changelog addition from the UBI image update? I think I also had a formatting error on the link to the PR. 

Also, I assume this is what the 1.0 contents would look like? Do we intend to remove the Beta1-5 changelings? That is typically what Core does and @ishustava seemed to suggest we do the same.

**Comment by curtbushko** [comment]
@david-yu I pulled in your UBI change.

I am not too sure about cleaning up the changelog and removing Beta1-5. This pass was to make sure that we caught all the content from PRs in the last while.

**Comment by david-yu** [comment]
@curtbushko I see. Perhaps we can do the cleanup in this PR too. Lets wait until @ishustava comes back for air to see if there is alignment on cleaning up the changelog.

**Review by david-yu — APPROVED** [review]

**Comment by david-yu** [comment]
Will approve for now, we can do a separate PR to move/remove beta release notes if needed.

**Review by thisisnotashwin — APPROVED** [review]

**Pull request merged**
