### PR TITLE
Reorg v2 controllers

### PR DESCRIPTION
**Pull request by jm96441n**
### Changes proposed in this PR ###  
- Reorganize v2 resource controllers from the `config-entries` package to the `resources` package to better indicate what that they are for controlling resources and not config-entries
- rename `ReconcileEntry` method on `ResourcesController` to be `ReconcileResource`

### How I've tested this PR ###
- ran tests

### How I expect reviewers to test this PR ###
- run tests
- :eye: 

### Checklist ###
- [ ] Tests added
- [ ] [CHANGELOG entry added](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Review by thisisnotashwin — APPROVED** [review]
nice!! i like the re-org!

**Review by DanStough — COMMENTED** [review]
I wonder if instead of:
* `control-plane/resources/controllers`
* `control-plane/config-entries/controllers`
it would make more sense to have:
* `control-plane/controllers/resources`
* `control-plane/controllers/config-entries`

I think this would be cleaner and meets the original intent, which is controllers that are shared with catalog sync live outside the `connect-inject` folder. I suspect that other v2 controllers will migrate here as well as we come back to catalog sync. I'll take @thisisnotashwin to verify the catalog-sync shared point because he knows infinitely more about it than I do 🧠 .

**Comment by jm96441n** [comment]
@DanStough I like that in that it's a bit cleaner around "controllers live here" and then which controllers are specified by the package

**Review by DanStough — APPROVED** [review]
LGTM, conditional on the unit* test that's failing. Looks like maybe it needs to reference the new controller location.

**Pull request merged**
