### PR TITLE
Fix failing ingress-gateway tests

### PR DESCRIPTION
**Pull request by wilkermichael**
Changes proposed in this PR:
- This fixes the failing ingress gateway tests
- Failures were caused from using an older version of consul dataplane, bumped the version to the latest nightly dev build of dataplane `1.0`

How I've tested this PR:
👀 

How I expect reviewers to test this PR:
👀 

Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Review by curtbushko — APPROVED** [review]

**Review by DanStough — APPROVED** [review]
I think we need to make sure in the post-release steps for k8s we flip these values back from the official images to the dev images.

**Comment by wilkermichael** [comment]
> I think we need to make sure in the post-release steps for k8s we flip these values back from the official images to the dev images.

Yeah, we do flip them to the official versions as part of the release steps

**Comment by wilkermichael** [comment]
@curtbushko I have an additional flake that passes locally for peering CNI: https://github.com/hashicorp/consul-k8s-workflows/actions/runs/5359646126/jobs/9730377397

potentially could be related to the CNI issues we've been seeing lately. 

We can discuss Monday, but probably okay to get this fix in and then analyze once CNI is fixed.

**Comment by wilkermichael** [comment]
CNI Peering tests are still failing but that is due to CNI testing issues in our pipeline that effects all branches. All tests pass locally.

**Pull request merged**
