### PR TITLE
GH-3406 - Only error for config entries from different datacenters when the config entries are different

### PR DESCRIPTION
**Pull request by jmurret**
Fixes https://github.com/hashicorp/consul-k8s/issues/3406

### Changes proposed in this PR ###  
-
-

### Checklist ###
- [ ] Tests added
- [ ] [CHANGELOG entry added](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Review by zalimeni — APPROVED** [review]

**Comment by zalimeni** [comment]
Confirmed this will only need backporting in `release/1.4.x` (file DNE prior)

**Comment by komapa** [comment]
LGTM, but can we backport all the way to 1.1.x? Thank you!

**Comment by jmurret** [comment]
It looks like there is more logic to consider with the migrate-entry annotation (`TestConfigEntryController_Migration`) that needs to be considered more closely.  will take a look tomorrow.

**Comment by david-yu** [comment]
@komapa I assume the same config entry is applied perhaps via Argo on different DCs that have the same name and same config? Also to be clear the CRD is applied on different clusters that are connected to different external servers is that correct? If so I agree that they should be marked as duplicate since they are different. If you have a test case we should explicitly check for that would be helpful.

**Comment by komapa** [comment]
> @komapa I assume the same config entry is applied perhaps via Argo on different DCs that have the same name and same config? Also to be clear the CRD is applied on different clusters that are connected to different external servers is that correct? If so I agree that they should be marked as duplicate since they are different. If you have a test case we should explicitly check for that would be helpful.

Yes, this is the exact use case. We have developers deploy from shared Kustomize templates and they can deploy to one region (one consul datacenter) or another region (another consul datacenter) or to both (the datacenters are WAN federated). So we do not really have the ability to only put the CRDs in one or the other.

I realize this is not idea, but only because of the way the Kubernetes functionality is not a great use-case for WAN federated clusters. We are kind of asking here to meet us in the middle and not hard fail reconciliation when the contents of the config entry are identical. You should still fail like you do not if they ever get out of sync.

**Pull request merged**
