### PR TITLE
Fix Gateway API CRDs

### PR DESCRIPTION
**Pull request by t-eckert**
It looks like the `copywrite` CLI deleted the Gateway CRDs we install. This would have broken us if it was released. I regenerated the external CRDs and added them to the Copywrite ignore given they are just pulled in from the Gateway SIG anyway and are not our IP.

Changes proposed in this PR:
- Regenerate external Gateway CRDs
- Remove errant .yml
- Add external CRDs to copywrite ignore

### CODE REVIEW

**Review by david-yu — APPROVED** [review]

**Comment by david-yu** [comment]
Thanks does this need to be backported?

**Comment by t-eckert** [comment]
> Thanks does this need to be backported?

I was just looking at that. The regression did not get into 1.2.x so we are fine there. I don't see a release branch cut for 1.3.x yet so I don't think it needs backporting.

**Review by nathancoleman — APPROVED** [review]
Glad you found this!

**Comment by nathancoleman** [comment]
@t-eckert it looks like there's a `release/1.3.0-rc1` [branch](https://github.com/hashicorp/consul-k8s/tree/release/1.3.0-rc1) as of a couple hours ago that we probably want to port this into

**Comment by NicoletaPopoviciu** [comment]
@curtbushko FYI

**Comment by t-eckert** [comment]
Lol, timing issue. I will do a manual backport.

**Comment by t-eckert** [comment]
Oh, I guess I was looking for `1.3.x` not `1.3.0-rc1`. Don't we normally have that first branch and branch into the latter?

**Comment by t-eckert** [comment]
Created #3066

**Comment by nathancoleman** [comment]
It looks to me like the copyright headers did make it into [1.2.0](https://github.com/hashicorp/consul-k8s/blob/v1.2.1/control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml), [1.2.1](https://github.com/hashicorp/consul-k8s/blob/v1.2.1/control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml) and [1.2.2](https://github.com/hashicorp/consul-k8s/blob/v1.2.2/control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml). Based on this, I'm going to backport to `release/1.2.x`.

**Pull request merged**
