### PR TITLE
[API Gateway] Add acceptance test for cluster peering

### PR DESCRIPTION
**Pull request by andrewstucki**
Changes proposed in this PR:
This adds an acceptance test for cluster peering with API gateways. It depends on this fix https://github.com/hashicorp/consul/pull/17609 landing in Consul with how we construct synthesized discovery chains, so it will need to land after that gets merged and a docker image is cut.

How I've tested this PR:
Ran acceptance test with fixed version of Consul and it passes.

Checklist:
- [x] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by andrewstucki** [comment]
Just FYI there are a couple of commits at the end here that I threw in because of a new added job in the workflows that's causing linter failures on tests unrelated to the code added. This is keeping CI from actually running the tests, so hacked together fixes for them. Let me know if I should revert prior to merge so the folks that wrote the tests can fix them properly if need be.

**Comment by wilkermichael** [comment]
A reminder that the 1.2.x branch is currently under a code freeze. If this isn't a bug fix/test introduction, and unless it's a critical feature for the 1.2.x-rc can you please refrain from merging this until after the 1.2.0-rc1 release (Tuesday, June 13th)

**Comment by andrewstucki** [comment]
Thanks for the reminder, this is just a test introduction, so it should be good for merge once tests are passing on the latest Consul build

**Review by missylbytes — APPROVED** [review]
LGTM

**Pull request merged**
