### PR TITLE
fix permissions for /consul/extra-config

### LINKED ISSUE #1306: can't create directory '/consul/extra-config': Permission denied
### Overview of the Issue

There's a little snippet introduced by hashicorp/consul-helm#1042 trying to `mkdir -p /consul/extra-config` which results in `mkdir: can't create directory '/consul/extra-config': Permission denied` on openshift / okd clusters.

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  enablePodSecurityPolicies: true
  openshift:
    enabled: true
```
2. Observe the error on openshift / okd v4 clusters.

### Environment details

- `consul-k8s` version: 0.45.0
- Kubernetes version: v1.23.5
- Cloud Provider: Openstack / OpenShift 4.10
- Networking CNI plugin in use: OpenShiftSDN

### PR DESCRIPTION
**Pull request by eb4x**
On openshift/okd you might not have permissions to create directories
everywhere. But you can introduce mounts.

Here we're just creating insignificant mount-points for the extra-config
to do it's thing, thus eliminating the need for creating the directory,
which the user running the container might not have permissions to do.

Fixes #1306

### CODE REVIEW

**Comment by jmurret** [comment]
Thank you so much @eb4x!  Could you add bats test to verify the existence of the volume and volume mounts for both client-daemonset.bats and server-statefulset.bats?  
The documentation for adding bats tests is here:  https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#writing-unit-tests

An example of testing for the existence of a volume and a volume mount is here: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/test/unit/client-daemonset.bats#L1738-L1758

**Comment by eb4x** [comment]
With the introduction of a new volume, I broke some tests which were dependent on volumes arranged in a fixed order, I can cherry-pick the fix in question provided from #1313, or maybe that can get reviewed and merged first.

**Review by jmurret — CHANGES_REQUESTED** [review]
Thank you @eb4x!  Related to my note on the other PR, please add those tests here for a complete PR and also revert the checksum tests to their original logic and update the latest checksums from your failed tests.

**Review by jmurret — APPROVED** [review]
Thank you @eb4x!  This looks good!

**Comment by kschoche** [comment]
Hi @eb4x! Thanks for submitting this PR, I was taking a quick look at it today and noticed that our CI did not run against it yet and so before approving I wanted to be sure it passed our acceptance tests. Right now it is failing the snapshot_agent test and I'm not immediately sure why, but if you have a chance to take a look that would be great. I'll circle back to this and look as well soon.
Cheers.

**Review by kschoche — APPROVED** [review]
I ran the failing tests manually locally and they passed, I believe they were failing in CI due to missing credentials.

This looks great, thanks!

**Pull request merged**
