### PR TITLE
Remove ECR tags for docker images

### PR DESCRIPTION
**Pull request by ishustava**
Changes proposed in this PR:
- We don't need to publish to ECR

How I've tested this PR:

How I expect reviewers to test this PR:

Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Review by thisisnotashwin — APPROVED** [review]
🙏

**Review by curtbushko — APPROVED** [review]
Sorry about that. I must have added that when I was using another repo (or their example) as a reference!

**Comment by ishustava** [comment]
> Sorry about that. I must have added that when I was using another repo (or their example) as a reference!

all good! I saw it too and didn't question it 😄

**Comment by ilpianista** [comment]
@ishustava `consul-k8s-control-plane` images are missing on ECR, while `consul` and `consul-dataplane` are present. Maybe you need to revert this?

**Comment by lkysow** [comment]
@ilpianista we only publish to ECR to enable our ECS integration since in some cases ECS can't pull from non-ECR repositories. For Kubernetes this isn't a requirement (at least last we tried it) so that's why we don't publish k8s images to ECR. Is that assumption incorrect for your use-case? Thanks for your help!

**Comment by ilpianista** [comment]
@lkysow your assumption is still right. Initially I thought this was a bug because several hashicorp Docker images are on ECR (even `vault` or the `vault-csi-provider`) while only `consul-k8s-control-plane` is missing.

**Comment by david-yu** [comment]
@ilpianista I think this would be a feature request to consider in the future, could you file an issue so we could start to track this request?

**Comment by ilpianista** [comment]
Done, #3091.

Thanks!

**Pull request merged**
