### PR TITLE
Update test to match PreparedQuery SamenessGroup bugfix.

### PR DESCRIPTION
**Pull request by hashi-derek**
Update test to assert the fixed behavior of PR #7773 in Consul Enterprise.

https://github.com/hashicorp/consul/pull/19970

### CODE REVIEW

**Review by wilkermichael — APPROVED** [review]
Thank you for updating the test, looks good!

**Review by wilkermichael — CHANGES_REQUESTED** [review]
I looked again, I think 1.2.x doesn't have the sameness tests so remove that label.

Also just a reminder not to merge the 1.3.x backport until after code freeze tomorrow.

**Review by wilkermichael — APPROVED** [review]
Nevermind, 1.2.x **does** have the tests. All good! disregard my last comment

**Comment by t-eckert** [comment]
@hashi-derek, echoing what @wilkermichael said. There is a code freeze on `1.{1-3}.x` for now so please do not merge those backports.

**Pull request merged**
