### PR TITLE
Add stanza to ci.hcl to trigger helm pipeline

### PR DESCRIPTION
**Pull request by shore**
Changes proposed in this PR:
- Trigger release pipeline via CRT process

How I've tested this PR:
- The new workflow has been tested generate the same parameters when invoking the existing pipeline for publishing helm charts

### CODE REVIEW

**Review by alvin-huang — APPROVED** [review]

**Review by curtbushko — APPROVED** [review]
Thank you!

**Review by kschoche — APPROVED** [review]
🔥

**Comment by david-yu** [comment]
Thank you @shore and @alvin-huang !

**Comment by curtbushko** [comment]
I will merge this after the upcoming release.

**Pull request merged**
