### PR TITLE
Update mesh CRD with MeshHTTPConfig.

### PR DESCRIPTION
**Pull request by thisisnotashwin**
Changes proposed in this PR:
- Update the Mesh CRD with Mesh HTTP Config.
- Update acceptance API version.

How I've tested this PR:
- Unit tests.
- Deploying on local cluster.
How I expect reviewers to test this PR:
- 👀 

Checklist:
- [x] Tests added
- [x] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by david-yu** [comment]
Thank you for doing this!

**Review by ndhanushkodi — APPROVED** [review]
Looks great!!

**Review by jmurret — APPROVED** [review]
Nice!  Thank you for doing this!

**Comment by thisisnotashwin** [comment]
> Why does acceptance use API v1.10.something, when it was using v1.12.0? It went back 2 versions?

That is an excellent question. The versioning on the API project has gotten messed up which is why even though that SHA is from a commit that was pushed yesterday, the version still says 1.10. hopefully this is something we do fix after 1.13 but it looks pretty bad. we still are using the latest API changes though.

**Pull request merged**
