### PR TITLE
Run API Gateway with no local agents

### PR DESCRIPTION
**Pull request by andrewstucki**
Changes proposed in this PR:

- This adds the ability to run and api gateway when local clients are disabled. It coincides with TTL-based health checks being the norm for our deployment entrypoint [here](https://github.com/hashicorp/consul-api-gateway/pull/371).

How I've tested this PR:

- Unit tests and manually.

Checklist:
- [x] Tests added
- [x] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by mikemorris** [comment]
Is the `externalServers` conditional wrapping because consul-k8s doesn't support disabling clients with cluster-hosted servers yet?

**Comment by david-yu** [comment]
@andrewstucki Is this ready for review? Feel free to add the consul-k8s team and it should auto assign reviewers.

**Comment by andrewstucki** [comment]
Yep @david-yu it should be ready to go

**Comment by david-yu** [comment]
@andrewstucki Was briefly chatting with @ishustava and she mentioned there is a ton of agentless changes that may impact this PR. Also she asked is this only supposed to use external servers and noticed that it looks like its still using HOST_IP in some configurations.

**Comment by andrewstucki** [comment]
@david-yu : Ah, see that I missed that the agentless stuff was all going into `agentless-base` branch, I'll rebase the work off of there and clean it up.

**Pull request closed without merging**
