### PR TITLE
build: Create arm64 packages as well

### PR DESCRIPTION
**Pull request by dekimsey**
### Changes proposed in this PR ###  

During the CRT on-boarding, packaging for other Linux architectures (arm64) was
not enabled. This change adds packaging support for those architectures. I've
specifically opted not to include 32-bit.

Other related updates:

 - To make future support a bit easier, I've enabled the build workflow from
   releng prefixed branches.
 - Using qemu emulation for testing package installs on other architectures,
   thus allowing us to validate the binaries work as intended
 - Minor alteration to the package install tests to use yum instead of rpm

Note: I tried to add 386/arm packages but pivoted away. There's something suspicious with the 386 binary specifically (see comments). Since usage of that architecture is low, I punted.

### How I've tested this PR ###

Please note, these packages have not been extensively tested on their respective platforms. I did update the pipeline to run the smoke test (consul version) against the arm64 packages in an arm64 user-space. So I think it's in a good place.

### How I expect reviewers to test this PR ###

Download builds and test in the same manner existing binaries are tested. Docker containers would be sufficient.

### Checklist ###
- [x] ~~Tests added~~
- [x] [CHANGELOG entry added](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry) 

### Related ###

See #1132.
Related to hashicorp/releng-support#178.

### CODE REVIEW

**Comment by david-yu** [comment]
@dekimsey I assume this would also solve https://github.com/hashicorp/consul-k8s/issues/3504?

**Review by david-yu — APPROVED** [review]

**Comment by dekimsey** [comment]
@david-yu Yes, it will. Previously we were [building](https://github.com/hashicorp/consul-k8s/actions/runs/7806107711):

  -  consul-k8s-1.5.0~dev-1.x86_64.rpm 
  -  consul-k8s_1.5.0~dev-1_amd64.deb 
  -  consul-k8s-fips-1.5.0~dev+fips1402-1.x86_64.rpm
  -  consul-k8s-fips_1.5.0~dev+fips1402-1_amd64.deb 

With this change, we'll have the following additional packages produced in the build pipeline:

  -  consul-k8s_1.5.0~dev-1_arm64.deb 
  - consul-k8s-1.5.0~dev-1.aarch64.rpm
  -  consul-k8s-fips_1.5.0~dev+fips1402-1_arm64.deb
  - consul-k8s-fips-1.5.0~dev+fips1402-1.aarch64.rpm 
 
CRT will distribute them to the appropriate repositories when the time comes. The 32-bit architectures (arm, 386) are excluded. It would be possible to add arm but 386 is suspect.

### Changes made since the review:

While double-checking the work to answer your question, I found the rpm 32-bit installs failed when attempting to test their install in clean docker environments (tests, awesome!). I attempted to enable them, but found they had problems (see below).

In order to test the installs of the packages, I've added a step to enable qemu and then updated the test to test with the architecture of the package instead of amd64.

Minor change to the package install tests to use yum over rpm to better exercise how they would be installed in the field.

<details><summary>386 segfault</summary>

Interestingly, [running](https://github.com/hashicorp/consul-k8s/actions/runs/7817930985/job/21326994065#step:15:96) the 386 binary in the 386 userspace revealed a segfault which could be golang/go#64935. Bumping the minimum Go version to 1.21.7 only removed the traceback, but didn't seem to address the issue. It's not clear to me if this is a 386 issue or an emulation issue. I don't know/how we are testing the 386 architecture so I don't know if this is an existing issue.

Go 1.21.6:
```
SIGSEGV: segmentation violation
PC=0x80964cf m=1 sigcode=1

goroutine 0 [idle]:
runtime.runqput(0x0, 0xcc06400, 0x1)
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:6206 +0xaf fp=0x41000dc8 sp=0x41000da8 pc=0x80964cf
runtime.newproc.func1()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:4484 +0x56 fp=0x41000ddc sp=0x41000dc8 pc=0x8091de6
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_386.s:374 +0x41 fp=0x41000de0 sp=0x41000ddc pc=0x80b8671

goroutine 1 [running, locked to thread]:
	goroutine running on other thread; stack unavailable

goroutine 2 [runnable]:
runtime.forcegchelper()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:313 fp=0xcc67ff0 sp=0xcc67fec pc=0x80893d0
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_386.s:1363 +0x1 fp=0xcc67ff4 sp=0xcc67ff0 pc=0x80b9a01
created by runtime.init.5 in goroutine 1
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:310 +0x23
```

vs [running](https://github.com/hashicorp/consul-k8s/actions/runs/7818321501/job/21331388493#step:15:88) from a Go 1.21.7 built package:
```
SIGSEGV: segmentation violation
PC=0x809667f m=1 sigcode=1

goroutine 0 [idle]:
runtime.runqput(0x0, 0xcc06400, 0x1)
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/proc.go:6201 +0xaf fp=0x41000dc8 sp=0x41000da8 pc=0x809667f
runtime.newproc.func1()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/proc.go:4479 +0x56 fp=0x41000ddc sp=0x41000dc8 pc=0x8091f96
runtime.systemstack()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/asm_386.s:374 +0x41 fp=0x41000de0 sp=0x41000ddc pc=0x80b8801

goroutine 1 [running, locked to thread]:
	goroutine running on other thread; stack unavailable

goroutine 2 [runnable]:
runtime.forcegchelper()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/proc.go:313 fp=0xcc68ff0 sp=0xcc68fec pc=0x80895e0
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/asm_386.s:1363 +0x1 fp=0xcc68ff4 sp=0xcc68ff0 pc=0x80b9b91
created by runtime.init.5 in goroutine 1
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/proc.go:310 +0x23

```

**Comment by david-yu** [comment]
Thanks @dekimsey I am in favor of adding arm64 but 386 can disabled, and arm is not necessarily required since its 32 bit arm. Could you also update the description and title of the PR once the changes are stabilized?

**Review by david-yu — APPROVED** [review]
Approving, but will wait for another engineering team member to review.

**Comment by NicoletaPopoviciu** [comment]
adding @thisisnotashwin as a reviewer; thank you

**Review by thisisnotashwin — APPROVED** [review]
tysm

**Pull request merged**
