### PR TITLE
Fix CVEs by updating controller-runtime

### PR DESCRIPTION
**Pull request by t-eckert**
Fixes https://hashicorp.atlassian.net/browse/NET-704

Changes proposed in this PR:
- Bump version of controller runtime
- Update all breaking changes for this fix

How I've tested this PR:
- Built and run unit tests

How I expect reviewers to test this PR:

Checklist:
- [ ] Tests added
- [x] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by david-yu** [comment]
Thank you!

**Comment by curtbushko** [comment]
@t-eckert It looks like there are some conflicts. We so many changes going on as of late, I bet a few files changed under you.

**Review by curtbushko — CHANGES_REQUESTED** [review]
Thanks for this Thomas!  

This looks like a tedious amount of work so thank you for doing it.

I am not seeing anything wrong with it other than you checked in the control-plane binary 😉 

I suspect that the backports will fail miserably because of the go.mod/go.sum changes...

**Comment by david-yu** [comment]
Perhaps this should target 1.1.x instead of main? Also we should backport to 1.0.x if you can.

**Review by curtbushko — APPROVED** [review]

**Pull request merged**
