### PR TITLE
Manual backport of test: remove unused workflow inputs (#2589) into release/1.1.x

### PR DESCRIPTION
**Pull request by zalimeni**
I think this should resolve errors like https://github.com/hashicorp/consul-k8s/actions/runs/5615117399/job/15215290442?pr=2604#step:2:17 due to the missing arg in the target workflow.

Follow-up to #2589.

Checklist:
- [ ] Tests added
- [ ] [CHANGELOG entry added](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Review by DanStough — APPROVED** [review]
🚀

**Review by curtbushko — APPROVED** [review]

**Comment by zalimeni** [comment]
Force pushed to try a quick cache bust in case that was contributing to `golangci-lint` timeout issues re: https://github.com/golangci/golangci-lint-action/issues/730. I'll see if adding a timeout fixes it, and will add some debug logging around memory and CPU so we can diagnose if it happens again. Appears cache-y since it looks specific to my PR, not even just this release branch given https://github.com/hashicorp/consul-k8s-workflows/actions/runs/5602459151/job/15177096250#step:6:50 went through fine.

**Comment by zalimeni** [comment]
Attempting to resolve cache issues via
* https://github.com/hashicorp/consul-k8s-workflows/pull/29
* https://github.com/hashicorp/consul-k8s/pull/2621

**Comment by zalimeni** [comment]
Bringing in fix from https://github.com/hashicorp/consul-k8s/pull/2621 to get this to pass

**Pull request merged**
