### PR TITLE
Support configuring ACL Default Policy for Clients

### PR DESCRIPTION
**Pull request by lawliet89**
For boostraping an already in use Consul cluster. This PR will allow users of Consul API which are not managed by the Helm chart to continue accessing Consul without ACL tokens until they are migrated over.

### CODE REVIEW

**Comment by lawliet89** [comment]
@lkysow Any chance this could be reviewed?

**Comment by lawliet89** [comment]
@lkysow May I trouble you to get this reviewed please.

**Comment by david-yu** [comment]
Hi @lawliet89 thanks for the PR. I'll see if the team can take at this PR!

**Comment by ishustava** [comment]
Hey @lawliet89 

We currently already support that by setting that configuration via `server.extraConfig` or `client.extraConfig`. This configuration is always passed last to the `consul agent` command, and so it'll overwrite any configuration we set in the chart.

**Comment by lawliet89** [comment]
Hey @ishustava, so you are saying if I add that to `extraConfig`, it will be fine as it is and this is actually not needed? If so, that's good to know. Please feel free to close the PR.

**Comment by ishustava** [comment]
>so you are saying if I add that to extraConfig, it will be fine as it is and this is actually not needed?

yep, exactly!

Ok, closing the PR. Let me know if you run into any issues.

**Comment by lawliet89** [comment]
Thanks @ishustava. It works, as you have suggested.

**Pull request closed without merging**
