### PR TITLE
Remove CircleCI

### PR DESCRIPTION
**Pull request by curtbushko**
Changes proposed in this PR:
- Remove CircleCI from main

How I've tested this PR:

👀 

How I expect reviewers to test this PR:

👀 

Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by thisisnotashwin** [comment]
Is there a config we have to update on the repo to remove this:
image

**Review by thisisnotashwin — APPROVED** [review]
WOOOOOOOOO!!!!

**Comment by zalimeni** [comment]
> > Is there a config we have to update on the repo to remove this:
> 
> @thisisnotashwin I think it goes away once CircleCI is out of main all together.

That'll work for branches where it's gone, but as long as the CircleCI-managed webhook for the repo still exists in GH (and the GH org is connected and at least one follower has access to the repo), it'll continue building on branch pushes and scheduled workflows where the `.circleci/config.yml` exists. Once we're certain we don't want to do that anywhere anymore, a repo admin (GH) can go to CCI `Project Settings -> Overview -> Stop Building` to wipe the webhook and deploy key:
image

**Comment by curtbushko** [comment]
> > > Is there a config we have to update on the repo to remove this:
> > 
> > 
> > @thisisnotashwin I think it goes away once CircleCI is out of main all together.
> 
> That'll work for branches where it's gone, but as long as the CircleCI-managed webhook for the repo still exists in GH (and the GH org is connected and at least one follower has access to the repo), it'll continue building on branch pushes and scheduled workflows where the `.circleci/config.yml` exists. Once we're certain we don't want to do that anywhere anymore, a repo admin (GH) can go to CCI `Project Settings -> Overview -> Stop Building` to wipe the webhook and deploy key: image
> 
> If an org admin requests project or org deletion from CCI support, the same thing should happen at that point too.

I pushed the Stop Building button when I merged :)

**Pull request merged**
