### PR TITLE
Support TLS with Vault for the sync catalog deployment

### PR DESCRIPTION
**Pull request by ishustava**
Changes proposed in this PR:
- Support TLS with Vault for the sync catalog deployment
- Depends on #889 

How I've tested this PR:
acceptance tests

How I expect reviewers to test this PR:
code review

Checklist:
- [x] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Review by kschoche — APPROVED** [review]
This is coming together swimmingly, looks great!

**Review by ndhanushkodi — APPROVED** [review]
Looks great!!

**Comment by ndhanushkodi** [comment]
Are we waiting till the end to add changelog?

**Comment by kschoche** [comment]
> Are we waiting till the end to add changelog?

Yes! I'm going to add a changelog with the PR that brings `consul-vault-base` into `origin/main`

**Pull request merged**
