### PR TITLE
Fix NET-704 CVEs (backport to 1.0.x)

### PR DESCRIPTION
**Pull request by t-eckert**
*Manual backport of #2196*

Changes proposed in this PR:
- Fixes the CVEs noted in NET-704

How I've tested this PR:

How I expect reviewers to test this PR:

Checklist:
- [ ] Tests added
- [x] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

### CODE REVIEW

**Comment by david-yu** [comment]
Thank you, I appreciate you doing this this helps us sustain both 1.0.x and 1.1.x for their lifecycle.

**Review by andrewstucki — APPROVED** [review]

**Review by curtbushko — APPROVED** [review]
Thanks for doing these backports!

**Comment by t-eckert** [comment]
I think the test failures are just flakiness. It looks like the usual culprits are failing for the usual reasons. I'll run it once more to see if I get lucky on this roll.

How do we feel about merging even if those flakey tests are failing? 👍🏻 or 👎🏻?

**Comment by andrewstucki** [comment]
Yeah, from the logs, looks like it's all "api unavailable" errors which randomly like to happen when test Consul instances don't come up fast enough in the integration tests. I'd be fine merging still:

```
    command_test.go:175: 
        	Error Trace:	/home/runner/actions-runner/_work/consul-k8s-workflows/consul-k8s-workflows/control-plane/subcommand/get-consul-client-ca/command_test.go:175
        	            				/home/runner/actions-runner/_work/consul-k8s-workflows/consul-k8s-workflows/control-plane/subcommand/get-consul-client-ca/asm_amd64.s:1594
        	Error:      	Received unexpected error:
        	            	api unavailable
        	Test:       	TestRun_ConsulServerAvailableLater
```

**Pull request merged**
